
const SET_AUTH = "SET_AUTH"
const GET_AUTH = "GET_AUTH"
const SET_PROF_PIC = "UPDATE_PROF_PIC"
const REMOVE_AUTH = "REMOVE_AUTH"
const AUTH_REMOVED = "AUTH_REMOVED"
const NO_AUTH = "NO_AUTH"
const MSG = "MSG"
const BKURL = "http://localhost:5000/"
const SEND_LOG= "SEND_LOG"
const SET_HISTORY = "SET_HISTORY"
const GET_HISTORY = "GET_HISTORY"

export {SET_AUTH, GET_AUTH, SET_PROF_PIC, REMOVE_AUTH,
  AUTH_REMOVED, NO_AUTH, MSG, BKURL, SEND_LOG, SET_HISTORY, GET_HISTORY};
